name: PyTest

on:
  push:
    branches:
      - 'main'


jobs:
  json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test with pytest
        run: |
          python3 test.py