name: PyTest

on:
  push:
    branches:
      - 'main'


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test_Step_With_Pytest
        run:  |
          pip install pytest pytest-cov
          pytest .

