name: PyTest

on:
  push:
    branches:
      - 'main'


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test_Step
        run:  |
          pip install -U pytest
          pytest test.py

